___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11) #11 items in the array starting at 0

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#Get a value at an index
arr[8]

8

In [5]:
#Get values in a range
arr[1:5] #from index 1 up to but not including index 5

array([1, 2, 3, 4])

In [6]:
#Get values in a range
arr[0:5] #from index 0 up to but not including index 5

array([0, 1, 2, 3, 4])

In [7]:
#Get values in a range
arr[:6] # everything up to but not including index 6

array([0, 1, 2, 3, 4, 5])

In [8]:
#Get values in a range
arr[5:] # everything starting at index 5 up to the end (INCLUDING the very last one up)

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [9]:
#Setting a value with index range (Broadcasting)
arr[0:5] = 100 # broadcast the value 100 from index 0 up to but not including index 5.

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
#Change Slice
slice_of_arr[:]=99 #broadcast 99 to EVERYTHING in the array

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [13]:
arr #the magic and DANGER of broadcasting

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [14]:
#To get a copy, need to be explicit
arr_copy = arr.copy() # !!!!!!!!!      BE EXPLICIT  with .copy()     !!!!!!!!!!!!!

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [34]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [16]:
arr #should still have 99s now.

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [35]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
#Indexing row
arr_2d[1] #row at index 1 (second row), all of it


array([20, 25, 30])

In [37]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0] #row al index 1 (second row), column at index 0 (column 1).

20

In [38]:
# Getting individual element value
arr_2d[1,1]

25

In [39]:
# 2D array slicing, use the ":" notation

#Shape (2,2) from top right corner
arr_2d[:2,1:] # everything up to but NOT including row index 2, from column index 1 up to an including the very last column.

array([[10, 15],
       [25, 30]])

In [40]:
#Shape bottom row
arr_2d[2] #row index 2 only, all columns.

array([35, 40, 45])

In [41]:
#Shape bottom row
arr_2d[2,:] #row index 2 only, all columns.

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [42]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
#Length of array
arr_length = arr2d.shape[1]
arr_length

10

In [44]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [30]:
arr2d[[2,4,6,8]] #returns only the requested rows with the fancy index.

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [45]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [32]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
bool_arr = arr>4

In [47]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
arr[bool_arr] #get all the ORIGINAL values from the ORIGINAL array that are true according to the boolean array.

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr[arr>2] #anothe more directo way to use boolean or conditional selection/filtering.

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
x = 6
arr[arr < x] #with a variable

array([1, 2, 3, 4, 5])

# Great Job!
